language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
script: bash -ex .travis-opam.sh
env:
  global:
    - DEPOPTS="*"
    - TESTS=true
  matrix:
    - OCAML_VERSION=4.03 PACKAGE="jwt" PINS="nocrypto"
    - OCAML_VERSION=4.04 PACKAGE="jwt" PINS="nocrypto"
    - OCAML_VERSION=4.05 PACKAGE="jwt" PINS="nocrypto"
    - OCAML_VERSION=4.06 PACKAGE="jwt" PINS="nocrypto"
os:
  - linux
